// Generates the land mask the flat map draws, once, at development time.
//
//   npx tsx scripts/build-world-mask.ts
//
// Why a mask rather than shipping map geometry: the flat map is a dot
// matrix (same look as the globe), so it only ever needs "is this grid
// cell land?" — one bit per cell. World-atlas land geometry is ~100 KB
// of coordinates that the browser would then have to project and
// rasterise on every render; this bakes the answer into a ~1.5 KB
// base64 string and leaves no map dependency in the app bundle.
//
// world-atlas and topojson-client are devDependencies used only here.

import { writeFile } from "node:fs/promises";
import path from "node:path";
import { feature } from "topojson-client";
import type { Topology } from "topojson-specification";

// 2.5-degree cells: fine enough to read as continents, coarse enough to
// stay under a few thousand SVG dots.
const COLS = 144;
const ROWS = 72;

type Ring = [number, number][];

function ringsOf(geometry: GeoJSON.Geometry): Ring[] {
  if (geometry.type === "Polygon") {
    return geometry.coordinates as unknown as Ring[];
  }
  if (geometry.type === "MultiPolygon") {
    return (geometry.coordinates as unknown as Ring[][]).flat();
  }
  return [];
}

/** Ray casting: is [lon, lat] inside this ring? */
function inRing(lon: number, lat: number, ring: Ring): boolean {
  let inside = false;
  for (let i = 0, j = ring.length - 1; i < ring.length; j = i++) {
    const [xi, yi] = ring[i];
    const [xj, yj] = ring[j];
    const straddles = yi > lat !== yj > lat;
    if (straddles && lon < ((xj - xi) * (lat - yi)) / (yj - yi) + xi) {
      inside = !inside;
    }
  }
  return inside;
}

async function main() {
  const topology = (await import(
    path.join(process.cwd(), "node_modules/world-atlas/land-110m.json"),
    { with: { type: "json" } }
  )) as { default: Topology };

  const land = feature(
    topology.default,
    topology.default.objects.land
  ) as unknown as GeoJSON.FeatureCollection;

  const rings = land.features.flatMap((f) => ringsOf(f.geometry));
  console.log(`${rings.length} rings`);

  const bits: number[] = [];
  for (let row = 0; row < ROWS; row++) {
    // Sample at the centre of each cell.
    const lat = 90 - ((row + 0.5) / ROWS) * 180;
    for (let col = 0; col < COLS; col++) {
      const lon = -180 + ((col + 0.5) / COLS) * 360;
      let inside = false;
      for (const ring of rings) {
        if (inRing(lon, lat, ring)) inside = !inside;
      }
      bits.push(inside ? 1 : 0);
    }
  }

  // Pack to bytes, then base64.
  const bytes = new Uint8Array(Math.ceil(bits.length / 8));
  bits.forEach((bit, i) => {
    if (bit) bytes[i >> 3] |= 128 >> (i & 7);
  });
  const base64 = Buffer.from(bytes).toString("base64");

  const file = `// GENERATED by scripts/build-world-mask.ts — do not edit by hand.
//
// One bit per grid cell of an equirectangular world, row-major from the
// north-west corner: 1 means the cell centre falls on land. Decoded once
// per page by decodeWorldMask() in flat-map.ts.

export const WORLD_MASK_COLS = ${COLS};
export const WORLD_MASK_ROWS = ${ROWS};
export const WORLD_MASK_BASE64 =
  "${base64}";
`;

  const out = path.join(process.cwd(), "src/lib/dashboard/world-mask.ts");
  await writeFile(out, file);
  console.log(
    `${bits.filter(Boolean).length}/${bits.length} land cells, ` +
      `${(base64.length / 1024).toFixed(1)} KB base64 -> ${path.relative(process.cwd(), out)}`
  );
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
