const OPENROUTER_URL = "https://openrouter.ai/api/v1/chat/completions";
const MODEL = "anthropic/claude-sonnet-4.5";

// This is the ONLY thing the AI is asked to decide for a report — which
// of the 6 dashboard categories a trait belongs in. Every other field
// (result, gene list, risk loci count, bibliography, explanatory
// sections) is extracted deterministically in prepare-report-text.ts, not
// generated by the model. A single classification call over a short
// excerpt has far less surface for hallucination than asking a model to
// transcribe or paraphrase clinical data — see DESIGN.md for the full
// rationale and the reasoning this replaced.
const CLASSIFY_SYSTEM_PROMPT = `You are classifying a single genetic test result into exactly one category for a patient dashboard.

Categories:
- HEALTH_CONDITIONS: polygenic risk for a health condition or disease (e.g. heart disease, macular degeneration, cancer risk)
- HEREDITARY_CONDITIONS: inherited single-gene / carrier conditions (e.g. carrier status for a rare recessive disease)
- PHARMACOLOGY: how the body responds to or metabolizes a drug or medication
- TRAITS: physical or behavioral traits (e.g. eye color, hair loss, earwax type)
- WELLNESS: diet, fitness, lifestyle, or biomarker/protein levels not framed as a disease risk (e.g. vitamin levels, cholesterol-related protein levels, caffeine metabolism)
- ANCESTRY: geographic or ethnic origin, haplogroups

Respond with ONLY a JSON object of the shape {"category": "ONE_OF_THE_SIX_VALUES_ABOVE"} — no markdown, no commentary.`;

export class OpenRouterNotConfiguredError extends Error {
  constructor() {
    super(
      "AI analysis is not configured. Set OPEN_ROUTER_API_KEY in the environment to enable it."
    );
    this.name = "OpenRouterNotConfiguredError";
  }
}

export function isAiConfigured(): boolean {
  return Boolean(process.env.OPEN_ROUTER_API_KEY);
}

function stripCodeFences(text: string): string {
  const trimmed = text.trim();
  const fenced = trimmed.match(/^```(?:json)?\s*([\s\S]*?)\s*```$/i);
  return fenced ? fenced[1] : trimmed;
}

// Sends a short (title + intro + result headline) excerpt to the model
// and asks for nothing but a category label. Returns the raw parsed JSON
// (unvalidated — the caller checks it against analysisCategorySchema).
export async function requestCategoryClassification(
  classificationContext: string
): Promise<unknown> {
  const apiKey = process.env.OPEN_ROUTER_API_KEY;
  if (!apiKey) {
    throw new OpenRouterNotConfiguredError();
  }

  const res = await fetch(OPENROUTER_URL, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${apiKey}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      model: MODEL,
      temperature: 0,
      max_tokens: 50,
      response_format: { type: "json_object" },
      messages: [
        { role: "system", content: CLASSIFY_SYSTEM_PROMPT },
        { role: "user", content: classificationContext },
      ],
    }),
  });

  if (!res.ok) {
    const body = await res.text().catch(() => "");
    throw new Error(
      `OpenRouter request failed (${res.status}): ${body.slice(0, 500)}`
    );
  }

  const data = (await res.json()) as {
    choices?: { message?: { content?: string } }[];
  };
  const content = data.choices?.[0]?.message?.content;
  if (!content) {
    throw new Error("OpenRouter returned an empty response");
  }

  try {
    return JSON.parse(stripCodeFences(content));
  } catch {
    throw new Error("OpenRouter returned a response that was not valid JSON");
  }
}
